import type { Metadata } from "next";
import { ReactNode } from 'react';


export const metadata: Metadata = {
  title: "Solunar. | Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="th">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}